name: Build Python source distribution

on:
  push:
    branches: actions

jobs:
  build-sdist:
    name: Build source distribution
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        persist-credentials: false
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.x"
    - name: Install packages
      run: |
        python3 -m pip install build
        python3 -m pip install pybind11@git+https://github.com/pybind/pybind11.git@c6c9a9e59b2b64393de0432aa6867ed27367912a
        sudo apt-get update
        sudo apt-get install -y cmake ninja-build libopenblas-dev
        # see https://cppbinder.readthedocs.io/en/latest/install.html#id1
        sudo apt-get install -y clang-15 llvm-15 libclang-15-dev llvm-15-dev
    - name: Build Binder
      run: |
        git clone https://github.com/RosettaCommons/binder.git ../binder
        cmake -G Ninja \
              -D LLVM_DIR=/usr/lib/llvm-15/lib/cmake/llvm \
              -D Clang_DIR=/usr/lib/llvm-15/lib/cmake/clang \
              -D pybind11_DIR=`python3 -c "import pybind11; print(pybind11.get_cmake_dir())"` \
              -B ../build \
              ../binder
        cmake --build ../build
        ctest --test-dir ../build --output-on-failure
        cmake --install ../build
    - name: Configure with Trilinos
      run: |
        # clone Trilinos
        git clone https://github.com/trilinos/Trilinos.git --depth 1 ../trilinos
        # copy in ROL
        rsync -ar --delete . ../trilinos/packages/rol
        cp pyrol/pyproject.toml ../trilinos/
        # configure (requires running Binder)
        cmake -G Ninja \
              -D CMAKE_BUILD_TYPE:STRING=RELEASE \
              -D CPACK_SOURCE_IGNORE_FILES="/packages/rol/example;/packages/rol/test;/packages/rol/tutorial;/packages/teuchos/core/test;/packages/teuchos/core/example;/packages/teuchos/numerics/test;/packages/teuchos/numerics/example;/packages/teuchos/parameterlist/test;/packages/teuchos/parameterlist/example;/packages/teuchos/parser/test;/packages/teuchos/parser/example;/packages/teuchos/remainder/test;/packages/teuchos/remainder/example;/packages/teuchos/comm/test;/packages/teuchos/comm/example" \
              -D BUILD_SHARED_LIBS:BOOL=ON \
              -D ROL_ENABLE_EXAMPLES:BOOL=OFF \
              -D ROL_ENABLE_PYROL:BOOL=ON \
              -D ROL_ENABLE_TESTS:BOOL=OFF \
              -D PyROL_BINDER_clang_include_dirs:PATH="${LLVM_PREFIX}/include" \
              -D PyROL_BINDER_LibClang_include_dir:PATH="${LLVM_PREFIX}/lib/clang/${LLVM_VERSION}/include" \
              -D PyROL_BINDER_GCC_TOOLCHAIN:PATH="${GCC_PREFIX}" \
              -D PYROL_ENABLE_BINDER:BOOL=ON \
              -D PYROL_ENABLE_BINDER_UPDATE:BOOL=ON \
              -D Trilinos_CPACK_SOURCE_GENERATOR="TGZ" \
              -D Trilinos_ENABLE_ALL_OPTIONAL_PACKAGES:BOOL=OFF \
              -D Trilinos_ENABLE_CPACK_PACKAGING=ON \
              -D Trilinos_ENABLE_EXAMPLES:BOOL=OFF \
              -D Trilinos_ENABLE_Fortran:BOOL=OFF \
              -D Trilinos_ENABLE_ROL:BOOL=ON \
              -D Trilinos_ENABLE_TESTS:BOOL=OFF \
              -B ../trilinos/build \
              ../trilinos
        # create reduced tarball
        cmake --build ../trilinos/build --target package_source
        # unpack reduced tarball
        tar -zxf `find ../trilinos/build -name "*-Source.tar.gz" -print -quit`
        mv `find . -name "trilinos-*-Source" -print -quit` pyrol
        # create source distribution from tarball
        python3 -m build --sdist pyrol
